// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: telemetry.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetIngress_SendPosition_FullMethodName = "/telemetry.FleetIngress/SendPosition"
)

// FleetIngressClient is the client API for FleetIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetIngressClient interface {
	SendPosition(ctx context.Context, in *PositionUpdate, opts ...grpc.CallOption) (*IngressResponse, error)
}

type fleetIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetIngressClient(cc grpc.ClientConnInterface) FleetIngressClient {
	return &fleetIngressClient{cc}
}

func (c *fleetIngressClient) SendPosition(ctx context.Context, in *PositionUpdate, opts ...grpc.CallOption) (*IngressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngressResponse)
	err := c.cc.Invoke(ctx, FleetIngress_SendPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetIngressServer is the server API for FleetIngress service.
// All implementations must embed UnimplementedFleetIngressServer
// for forward compatibility.
type FleetIngressServer interface {
	SendPosition(context.Context, *PositionUpdate) (*IngressResponse, error)
	mustEmbedUnimplementedFleetIngressServer()
}

// UnimplementedFleetIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetIngressServer struct{}

func (UnimplementedFleetIngressServer) SendPosition(context.Context, *PositionUpdate) (*IngressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPosition not implemented")
}
func (UnimplementedFleetIngressServer) mustEmbedUnimplementedFleetIngressServer() {}
func (UnimplementedFleetIngressServer) testEmbeddedByValue()                      {}

// UnsafeFleetIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetIngressServer will
// result in compilation errors.
type UnsafeFleetIngressServer interface {
	mustEmbedUnimplementedFleetIngressServer()
}

func RegisterFleetIngressServer(s grpc.ServiceRegistrar, srv FleetIngressServer) {
	// If the following call pancis, it indicates UnimplementedFleetIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetIngress_ServiceDesc, srv)
}

func _FleetIngress_SendPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetIngressServer).SendPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetIngress_SendPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetIngressServer).SendPosition(ctx, req.(*PositionUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetIngress_ServiceDesc is the grpc.ServiceDesc for FleetIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.FleetIngress",
	HandlerType: (*FleetIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPosition",
			Handler:    _FleetIngress_SendPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telemetry.proto",
}
